coding_style:
    php:
        indentation:
            general:
                use_tabs: false
                size: 4
            switch:
                indent_case: true
        spaces:
            general:
                linefeed_character: newline
            before_parentheses:
                function_declaration: false
                closure_definition: true
                function_call: false
                if: true
                for: true
                while: true
                switch: true
                catch: true
                array_initializer: false
            around_operators:
                assignment: true
                logical: true
                equality: true
                relational: true
                bitwise: true
                additive: true
                multiplicative: true
                shift: true
                unary_additive: false
                concatenation: false
                negation: false
            before_left_brace:
                class: true
                function: true
                if: true
                else: true
                for: true
                while: true
                do: true
                switch: true
                try: true
                catch: true
                finally: true
            before_keywords:
                else: true
                while: true
                catch: true
                finally: true
            within:
                brackets: false
                array_initializer: false
                grouping: false
                function_call: false
                function_declaration: false
                if: false
                for: false
                while: false
                switch: false
                catch: false
                type_cast: false
            ternary_operator:
                before_condition: true
                after_condition: true
                before_alternative: true
                after_alternative: true
                in_short_version: false
            other:
                before_comma: false
                after_comma: true
                before_semicolon: false
                after_semicolon: true
                after_type_cast: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: end-of-line
            if:
                opening: end-of-line
                always: true
                else_on_new_line: false
            for:
                opening: end-of-line
                always: true
            while:
                opening: end-of-line
                always: true
            do_while:
                opening: end-of-line
                always: true
                while_on_new_line: false
            switch:
                opening: end-of-line
            try:
                opening: end-of-line
                catch_on_new_line: false
                finally_on_new_line: false
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower

checks:
    php:
        useless_calls: true
        unused_variables: true
        unused_properties: true
        unused_parameters: true
        unused_methods: true
        unreachable_code: true
        too_many_arguments: true
        simplify_boolean_return: true
        no_empty_statements: true
        no_commented_out_code: true
        comparison_always_same_result: true
        avoid_useless_overridden_methods: true
        use_self_instead_of_fqcn: true
        uppercase_constants: true
        properties_in_camelcaps: true
        parameters_in_camelcaps: true
        overriding_parameter: true
        no_goto: true
        naming_conventions:
            local_variable: '^[a-z][a-zA-Z0-9]*$'
            abstract_class_name: ^Abstract|Factory$
            utility_class_name: 'Utils?$'
            constant_name: '^[A-Z][A-Z0-9]*(?:_[A-Z0-9]+)*$'
            property_name: '^[a-z][a-zA-Z0-9]*$'
            method_name: '^(?:[a-z]|__)[a-zA-Z0-9]*$'
            parameter_name: '^[a-z][a-zA-Z0-9]*$'
            interface_name: '^[A-Z][a-zA-Z0-9]*Interface$'
            type_name: '^[A-Z][a-zA-Z0-9]*$'
            exception_name: '^[A-Z][a-zA-Z0-9]*Exception$'
            isser_method_name: '^(?:is|has|should|may|supports)'
        function_in_camel_caps: true
        encourage_single_quotes: true
        classes_in_camel_caps: true
        avoid_todo_comments: true
        avoid_perl_style_comments: true
        avoid_multiple_statements_on_same_line: true
        align_assignments: false
        return_doc_comments: true
        check_method_contracts:
            verify_interface_like_constraints: true
            verify_documented_constraints: true
            verify_parent_constraints: true
        return_doc_comment_if_not_inferrable: true
        parameter_doc_comments: true
        remove_extra_empty_lines: true
        prefer_while_loop_over_for_loop: true
        phpunit_assertions: true
        param_doc_comment_if_not_inferrable: true
        optional_parameters_at_the_end: true
        newline_at_end_of_file: true
        fix_use_statements:
            remove_unused: true
            preserve_multiple: false
            preserve_blanklines: false
            order_alphabetically: true
        fix_line_ending: true
        avoid_unnecessary_concatenation: true
        avoid_fixme_comments: true

filter:
    excluded_paths:
        - vendor/*
        - spec/*

build_failure_conditions:
    - 'elements.rating(<= D).exists'
    - 'issues.new.exists'
    - 'project.metric("scrutinizer.quality", < 9)'
    - 'project.metric("scrutinizer.quality", < -0.5)'

build:
    nodes:
        php-5.4-lowest:
            environment:
                php: 5.4
                postgresql: false
                redis: false
            dependencies:
                override:
                    - composer update -n --prefer-stable --prefer-lowest
            tests:
                override:
                    - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
                    - composer validate
                    -
                        command: 'test/build.sh'
                        environment:
                            COMPOSER_FLAGS: '--prefer-stable --prefer-lowest'

        php-5.4:
            environment:
                php: 5.4
                postgresql: false
                redis: false
            dependencies:
                override:
                    - composer update -n
            tests:
                override:
                    - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
                    - composer validate
                    - test/build.sh
        php-5.5:
            environment:
                php: 5.5
                postgresql: false
                redis: false
            dependencies:
                override:
                    - composer update -n
            tests:
                override:
                    - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
                    - composer validate
                    - test/build.sh
        php-5.6:
            environment:
                php: 5.6
                postgresql: false
                redis: false
            dependencies:
                override:
                    - composer update -n
            tests:
                override:
                    - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
                    - composer validate
                    - test/build.sh
        php-7.0:
            environment:
                php: 7.0
                postgresql: false
                redis: false
            dependencies:
                override:
                    - composer update -n
            tests:
                override:
                    - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
                    - composer validate
                    - test/build.sh
        php-7.1:
            environment:
                php: 7.1
                postgresql: false
                redis: false
            dependencies:
                override:
                    - composer update -n
            tests:
                override:
                    - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
                    - composer validate
                    - test/build.sh
        php-7.2:
            environment:
                php: 7.2
                postgresql: false
                redis: false
            dependencies:
                override:
                    - composer update -n
            tests:
                override:
                    - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
                    - composer validate
                    - test/build.sh
        php-hhvm:
            environment:
                php: hhvm
                postgresql: false
                redis: false
            dependencies:
                override:
                    - composer update -n
            tests:
                override:
                    - find src -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
                    - composer validate
                    - test/build.sh
